spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3307/bank_service_db?useSSL=false&allowPublicKeyRetrieval=true  # Use Docker service name for MySQL, not localhost
    username: appuser
    password: apppass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: optional:configserver:http://localhost:8888

