server:
  port: 8222

management:
  tracing:
    sampling:
      probability: 1.0


spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb:http://account-service
          predicates:
            - Path=/account/**
        - id: transaction-service
          uri: lb:http://transaction-service
          predicates:
            - Path=/transaction/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/





